name: Deploy Django App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Prepare remote environment
        env:
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "\
            cd $REMOTE_DIR && \
            git fetch origin && \
            git checkout main && \
            git pull origin main"

      - name: Prepare database
        env:
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "\
            cd $REMOTE_DIR && \
            # Ensure database file exists and has proper permissions
            touch db.sqlite3 && \
            chmod 666 db.sqlite3"

      - name: Build Docker image
        env:
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "\
            cd $REMOTE_DIR && \
            docker build -t my-django-app ."

      - name: Deploy container
        env:
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "\
            cd $REMOTE_DIR && \
            docker stop my-django-app || true && \
            docker rm my-django-app || true && \
            docker run -d --name my-django-app \
              -p 8000:8000 \
              -v $REMOTE_DIR/db.sqlite3:/app/db.sqlite3 \
              -v $REMOTE_DIR/.env:/app/.env \
              my-django-app"
