name: Deploy Django App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Deploy to remote server
        env:
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          echo "Entering the remote server and updating the Git repository..."
          ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "\
            cd $REMOTE_DIR && \
            git fetch origin || echo 'Git fetch failed' && \
            git checkout main || echo 'Checkout to main branch failed' && \
            git pull origin main || echo 'Git pull failed'"

          echo "Building the Docker image for the Django app..."
          ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "\
            cd $REMOTE_DIR && \
            docker build -t my-django-app . || echo 'Docker build failed'"

          echo "Stopping and removing any existing Docker container..."
          ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "\
            docker stop my-django-app || true && \
            docker rm my-django-app || true"

          echo "Running the Docker container with the Django app..."
          ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "\
            docker run -d --name my-django-app -p 8000:8000 my-django-app || echo 'Docker run failed'"
